server:
  port: 8761
  ssl:
    key-store: classpath:certs/eureka-server-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: eureka-server
    trust-store: classpath:certs/eureka-server-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
