server:
  port: 8083
  ssl:
    key-store: classpath:certs/order-service-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: order-service
    trust-store: classpath:certs/order-service-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
spring:
  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server.demoapi.io:8761/eureka/
