server:
  port: 8082
  ssl:
    key-store: classpath:certs/product-service-keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: product-service
    trust-store: classpath:certs/product-service-truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
spring:
  application:
    name: product-service

eureka:
  client:
    service-url:
      defaultZone: https://eureka-server.demoapi.io:8761/eureka/
